// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPybcq8WhJdXA8CR357B6TZHNtvUUCYWI',
    appId: '1:783283476832:web:9eab249497195030716605',
    messagingSenderId: '783283476832',
    projectId: 'activity15-e0dd9',
    authDomain: 'activity15-e0dd9.firebaseapp.com',
    storageBucket: 'activity15-e0dd9.firebasestorage.app',
    measurementId: 'G-MRRKFT22RM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCebDBnPx_GOAMFGrBpczqVGlxAxasWe90',
    appId: '1:783283476832:android:19a459970c88b52e716605',
    messagingSenderId: '783283476832',
    projectId: 'activity15-e0dd9',
    storageBucket: 'activity15-e0dd9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPybcq8WhJdXA8CR357B6TZHNtvUUCYWI',
    appId: '1:783283476832:web:161f424fcaac2c59716605',
    messagingSenderId: '783283476832',
    projectId: 'activity15-e0dd9',
    authDomain: 'activity15-e0dd9.firebaseapp.com',
    storageBucket: 'activity15-e0dd9.firebasestorage.app',
    measurementId: 'G-31E9GNCJ74',
  );
}
